# Sanctum — sanctum-default-light variant
# Palette: github.com/jdanielmourao/obsidian-sanctum
background            #f4f4f0
foreground            #161616
cursor                #f68d45
cursor_text_color     #f4f4f0
selection_background  #e2e0dc
selection_foreground  #161616
url_color             #3f758f

active_tab_background   #f68d45
active_tab_foreground   #161616
inactive_tab_background #e2e0dc
inactive_tab_foreground #545151
active_border_color     #f68d45
inactive_border_color   #c7c5c2

color0  #161616
color8  #706e6d
color1  #9c2327
color9  #c54128
color2  #1d5e38
color10 #3f7b52
color3  #986400
color11 #b88300
color4  #325384
color12 #53709f
color5  #702fac
color13 #8f51cd
color6  #205677
color14 #3f758f
color7  #a9a8a5
color15 #c7c5c2
