color=faf4ed
bs-hl-color=b4637a
caps-lock-bs-hl-color=b4637a
caps-lock-key-hl-color=ea9d34
inside-color=fffaf3
inside-clear-color=fffaf3
inside-caps-lock-color=fffaf3
inside-ver-color=fffaf3
inside-wrong-color=fffaf3
key-hl-color=286983
layout-bg-color=faf4ed
layout-border-color=dfdad9
layout-text-color=575279
line-color=faf4ed
line-clear-color=faf4ed
line-caps-lock-color=faf4ed
line-ver-color=faf4ed
line-wrong-color=faf4ed
ring-color=dfdad9
ring-clear-color=56949f
ring-caps-lock-color=ea9d34
ring-ver-color=286983
ring-wrong-color=b4637a
separator-color=00000000
text-color=575279
text-clear-color=56949f
text-caps-lock-color=ea9d34
text-ver-color=286983
text-wrong-color=b4637a
