font=Inter 11
border-radius=6
default-timeout=5000
ignore-timeout=1
max-icon-size=32
margin=10
padding=10
background-color=#eff1f5
text-color=#4c4f69
border-color=#ccd0da
border-size=1

[urgency=high]
background-color=#d20f39
text-color=#eff1f5
border-color=#d20f39
