font=Inter 11
border-radius=6
default-timeout=5000
ignore-timeout=1
max-icon-size=32
margin=10
padding=10
background-color=#fdfefe
text-color=#161616
border-color=#e2e0dc
border-size=1

[urgency=high]
background-color=#c54128
text-color=#fdfefe
border-color=#c54128
