#!/usr/bin/bash
# Suppress kernel messages on this TTY
dmesg -n 1
exec tuigreet \
  --time \
  --user-menu \
  --user-menu-min-uid 1000 \
  --cmd "bash -c 'exec /usr/bin/zsh -l'" \
  --asterisks \
  --greet-align center \
  --kb-command 1 \
  --kb-sessions 2 \
  --kb-power 3 \
  --power-shutdown 'loginctl poweroff' \
  --power-reboot 'loginctl reboot' \
  --window-padding 2 \
  --container-padding 2 \
  --prompt-padding 1
