# Sanctum — sanctum-black variant (pure black background)
# Palette: github.com/jdanielmourao/obsidian-sanctum
background            #000000
foreground            #c7c5c2
cursor                #669961
cursor_text_color     #000000
selection_background  #262625
selection_foreground  #f4f4f0
url_color             #3f758f

active_tab_background   #669961
active_tab_foreground   #000000
inactive_tab_background #161616
inactive_tab_foreground #8e8c8b
active_border_color     #669961
inactive_border_color   #262625

color0  #262625
color8  #545151
color1  #c54128
color9  #f35a37
color2  #669961
color10 #89b46e
color3  #d59f25
color11 #f3bd4f
color4  #53709f
color12 #6891b5
color5  #a577da
color13 #ba9ae4
color6  #63959c
color14 #7db1b3
color7  #c7c5c2
color15 #f4f4f0
