font=Inter 11
border-radius=6
default-timeout=5000
ignore-timeout=1
max-icon-size=32
margin=10
padding=10
background-color=#161821
text-color=#c6c8d1
border-color=#1e2132
border-size=1

[urgency=high]
background-color=#e27878
text-color=#161821
border-color=#e27878
