font=Inter 11
border-radius=6
default-timeout=5000
ignore-timeout=1
max-icon-size=32
margin=10
padding=10
background-color=#191724
text-color=#e0def4
border-color=#403d52
border-size=1

[urgency=high]
background-color=#eb6f92
text-color=#e0def4
border-color=#eb6f92
