auth {
    fingerprint {
        enabled = true
        ready_message = Place your finger on the reader
        present_message = Scanning...
    }
}

background {
    monitor =
    path = ~/Pictures/wallpapers/wallpaper-1-3840.jpg
}
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(cba6f7)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(cdd6f4ff)
    font_size = 48
    font_family = Inter
    position = 0, 100
    halign = center
    valign = center
}
